// Copyright 2026 Code Philosophy

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ZLua.CppCodeGen
{
    internal sealed class AliasCodegen
    {
        private readonly string _outputDir;

        public AliasCodegen(string outputDir)
        {
            _outputDir = outputDir;
        }

        public void Generate()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            List<LuaAliasXmlRule> rules;
            try
            {
                LuaAliasXmlRegistry.Load(Settings.Instance.luaAliasXmlPaths, projectRoot);
                LuaAliasXmlRegistry.ValidateAllLoadedAssemblies();
                rules = new List<LuaAliasXmlRule>(LuaAliasXmlRegistry.Rules);
            }
            catch (Exception ex)
            {
                throw new Exception("[ZLua] LuaAlias XML load/validate failed during codegen: " + ex.Message, ex);
            }

            WriteHeader();
            WriteSource(rules);
            Debug.Log("[ZLua] AliasCodegen: emitted " + rules.Count + " XML rule(s).");
        }

        private void WriteHeader()
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by AliasCodegen. Do not edit.");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#define ZLUA_HAS_ALIAS_BINDINGS 1");
            writer.WriteLine();
            writer.WriteLine("namespace zlua");
            writer.WriteLine("{");
            writer.WriteLine("    void RegisterAliasBindingTables();");
            writer.WriteLine("}");
            writer.Save(Path.Combine(_outputDir, "AliasBindings.h"));
        }

        private void WriteSource(List<LuaAliasXmlRule> rules)
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by AliasCodegen. Do not edit.");
            writer.WriteLine("#include \"AliasBindings.h\"");
            writer.WriteLine("#include \"../mt/AliasXmlTable.h\"");
            writer.WriteLine();
            writer.WriteLine("namespace zlua");
            writer.WriteLine("{");
            // Named (not anonymous) so Il2Cpp lumping multiple generated/*.cpp into one TU does not collide.
            writer.WriteLine("namespace alias_bindings");
            writer.WriteLine("{");

            if (rules.Count > 0)
            {
                writer.WriteLine("static const LuaAliasXmlEntry kEntries[] = {");
                writer.IncreaseIndent();
                for (int i = 0; i < rules.Count; i++)
                {
                    LuaAliasXmlRule rule = rules[i];
                    writer.WriteLine("{");
                    writer.IncreaseIndent();
                    writer.WriteLine(ToCStringLiteral(rule.AssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.TypeFullName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.MethodName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.Signature) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.Alias) + ",");
                    writer.DecreaseIndent();
                    writer.WriteLine("},");
                }

                writer.DecreaseIndent();
                writer.WriteLine("};");
            }

            writer.WriteLine("} // namespace alias_bindings");
            writer.WriteLine();
            writer.WriteLine("void RegisterAliasBindingTables()");
            writer.WriteLine("{");
            writer.IncreaseIndent();
            if (rules.Count == 0)
            {
                writer.WriteLine("AliasXmlTable::Clear();");
            }
            else
            {
                writer.WriteLine("AliasXmlTable::RegisterEntries(alias_bindings::kEntries, sizeof(alias_bindings::kEntries) / sizeof(alias_bindings::kEntries[0]));");
            }

            writer.DecreaseIndent();
            writer.WriteLine("}");
            writer.WriteLine("} // namespace zlua");
            writer.Save(Path.Combine(_outputDir, "AliasBindings.cpp"));
        }

        private static string ToCStringLiteral(string value)
        {
            if (value == null)
            {
                return "\"\"";
            }

            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        if (c < 32 || c > 126)
                        {
                            sb.Append("\\x");
                            sb.Append(((int)c).ToString("x2"));
                        }
                        else
                        {
                            sb.Append(c);
                        }

                        break;
                }
            }

            sb.Append('"');
            return sb.ToString();
        }
    }
}
