// Copyright 2026 Code Philosophy

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ZLua.CppCodeGen
{
    internal sealed class ExtensionCodegen
    {
        private readonly string _outputDir;

        public ExtensionCodegen(string outputDir)
        {
            _outputDir = outputDir;
        }

        public void Generate()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            List<LuaExtensionXmlRule> rules;
            try
            {
                LuaExtensionXmlRegistry.Load(Settings.Instance.luaExtensionXmlPaths, projectRoot);
                LuaExtensionXmlRegistry.ValidateAllLoadedAssemblies();
                rules = new List<LuaExtensionXmlRule>(LuaExtensionXmlRegistry.Rules);
            }
            catch (Exception ex)
            {
                throw new Exception("[ZLua] LuaExtension XML load/validate failed during codegen: " + ex.Message, ex);
            }

            WriteHeader();
            WriteSource(rules);
            Debug.Log("[ZLua] ExtensionCodegen: emitted " + rules.Count + " XML rule(s).");
        }

        private void WriteHeader()
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by ExtensionCodegen. Do not edit.");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#define ZLUA_HAS_EXTENSION_BINDINGS 1");
            writer.WriteLine();
            writer.WriteLine("namespace zlua");
            writer.WriteLine("{");
            writer.WriteLine("    void RegisterExtensionBindingTables();");
            writer.WriteLine("}");
            writer.Save(Path.Combine(_outputDir, "ExtensionBindings.h"));
        }

        private void WriteSource(List<LuaExtensionXmlRule> rules)
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by ExtensionCodegen. Do not edit.");
            writer.WriteLine("#include \"ExtensionBindings.h\"");
            writer.WriteLine("#include \"../mt/ExtensionXmlTable.h\"");
            writer.WriteLine();
            writer.WriteLine("namespace zlua");
            writer.WriteLine("{");
            writer.WriteLine("namespace extension_bindings");
            writer.WriteLine("{");

            if (rules.Count > 0)
            {
                writer.WriteLine("static const LuaExtensionXmlEntry kEntries[] = {");
                writer.IncreaseIndent();
                for (int i = 0; i < rules.Count; i++)
                {
                    LuaExtensionXmlRule rule = rules[i];
                    writer.WriteLine("{");
                    writer.IncreaseIndent();
                    writer.WriteLine(ToCStringLiteral(rule.TargetAssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.TargetTypeFullName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.ExtensionAssemblyName) + ",");
                    writer.WriteLine(ToCStringLiteral(rule.ExtensionTypeFullName) + ",");
                    writer.DecreaseIndent();
                    writer.WriteLine("},");
                }

                writer.DecreaseIndent();
                writer.WriteLine("};");
            }

            writer.WriteLine("} // namespace extension_bindings");
            writer.WriteLine();
            writer.WriteLine("void RegisterExtensionBindingTables()");
            writer.WriteLine("{");
            writer.IncreaseIndent();
            if (rules.Count == 0)
            {
                writer.WriteLine("ExtensionXmlTable::Clear();");
            }
            else
            {
                writer.WriteLine(
                    "ExtensionXmlTable::RegisterEntries(extension_bindings::kEntries, sizeof(extension_bindings::kEntries) / sizeof(extension_bindings::kEntries[0]));");
            }

            writer.DecreaseIndent();
            writer.WriteLine("}");
            writer.WriteLine("} // namespace zlua");
            writer.Save(Path.Combine(_outputDir, "ExtensionBindings.cpp"));
        }

        private static string ToCStringLiteral(string value)
        {
            if (value == null)
            {
                return "\"\"";
            }

            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\':
                        sb.Append("\\\\");
                        break;
                    case '"':
                        sb.Append("\\\"");
                        break;
                    case '\n':
                        sb.Append("\\n");
                        break;
                    case '\r':
                        sb.Append("\\r");
                        break;
                    case '\t':
                        sb.Append("\\t");
                        break;
                    default:
                        if (c < 32 || c > 126)
                        {
                            sb.Append("\\x");
                            sb.Append(((int)c).ToString("x2"));
                        }
                        else
                        {
                            sb.Append(c);
                        }

                        break;
                }
            }

            sb.Append('"');
            return sb.ToString();
        }
    }
}
