// Copyright 2026 Code Philosophy

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace ZLua.CppCodeGen
{
    internal sealed class MarshalAsCodegen
    {
        private readonly string _outputDir;
        public MarshalAsCodegen(string outputDir)
        {
            _outputDir = outputDir;
        }


        public void Generate()
        {
            var writer = new CodeWriter();
            writer.WriteLine("// Generated by MarshalAsCodegen (Phase 8.1). Do not edit.");
            writer.WriteLine("#pragma once");
            writer.WriteLine();
            writer.WriteLine("#define ZLUA_HAS_MARSHAL_BINDINGS 1");
            writer.WriteLine();
            writer.WriteLine("namespace zlua");
            writer.WriteLine("{");
            writer.WriteLine("    inline void RegisterMarshalBindingTables() { }");
            writer.WriteLine("}");

            writer.Save(Path.Combine(_outputDir, "MarshalBindings.h"));
        }
    }
}
