// Copyright 2026 Code Philosophy

using System;
using System.IO;
using System.Text;
using UnityEngine;

namespace ZLua.Utils
{
    /// <summary>
    /// Writes <c>zlua/generated/ZLuaConf.inc</c> (spec 11-MULTI-VERSION §12).
    /// </summary>
    public static class ZLuaConfWriter
    {
        public const string FileName = "ZLuaConf.inc";

        public static string LocalConfPath =>
            Path.Combine(CommonDirs.GeneratedZLuaPath, FileName);

        public static string PackageStubPath =>
            Path.Combine(CommonDirs.PackageGeneratedZLuaPath, FileName);

        public sealed class ConfValues
        {
            public int UseLuaJit;
            public int LuaApiFamily;
            public int TuanjieEngine;
            public int UnityVersion;
            public int TuanjieVersion;
            public string ConfId;
        }

        public static ConfValues Build(LuaVersionInfo luaInfo, string unityVersionStr = null)
        {
            if (luaInfo == null)
            {
                throw new ArgumentNullException(nameof(luaInfo));
            }

            string unityStr = unityVersionStr ?? Application.unityVersion;
            var unityLine = new UnityVersion(unityStr);
            EngineVersionUtil.ResolveTuanjieFields(
                unityStr, out int tjFlag, out int tjCode, out string tjLabel);

            return new ConfValues
            {
                UseLuaJit = luaInfo.IsLuaJit ? 1 : 0,
                LuaApiFamily = EngineVersionUtil.EncodeLuaApiFamily(luaInfo),
                TuanjieEngine = tjFlag,
                UnityVersion = EngineVersionUtil.EncodeUnityVersion(unityLine),
                TuanjieVersion = tjCode,
                ConfId = EngineVersionUtil.BuildConfId(luaInfo.Id, unityLine, tjLabel),
            };
        }

        public static string FormatInc(ConfValues v)
        {
            var sb = new StringBuilder(512);
            sb.AppendLine("/* Generated by ZLua Install/Generate. Do not edit. */");
            sb.AppendLine($"#define ZLUA_USE_LUAJIT         {v.UseLuaJit}");
            sb.AppendLine($"#define ZLUA_LUA_API_FAMILY     {v.LuaApiFamily}");
            sb.AppendLine($"#define ZLUA_TUANJIE_ENGINE     {v.TuanjieEngine}");
            sb.AppendLine($"#define ZLUA_UNITY_VERSION      {v.UnityVersion}");
            sb.AppendLine($"#define ZLUA_TUANJIE_VERSION    {v.TuanjieVersion}");
            sb.AppendLine($"#define ZLUA_CONF_ID            \"{EscapeCString(v.ConfId)}\"");
            return sb.ToString();
        }

        /// <summary>Authoritative write to Local Il2Cpp tree (Install).</summary>
        public static void WriteLocal(LuaVersionInfo luaInfo, string unityVersionStr = null)
        {
            ConfValues values = Build(luaInfo, unityVersionStr);
            string dir = CommonDirs.GeneratedZLuaPath;
            Directory.CreateDirectory(dir);
            string path = Path.Combine(dir, FileName);
            File.WriteAllText(path, FormatInc(values), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            Debug.Log($"[ZLua] Wrote {FileName}: {values.ConfId}");
        }

        /// <summary>
        /// Generate/All: rewrite Local conf from current Settings / Editor version.
        /// Fails if Install has not produced a local zlua tree yet.
        /// </summary>
        public static void WriteOrRefreshLocalFromSettings()
        {
            if (!Directory.Exists(CommonDirs.LocalZluaPath))
            {
                throw new InvalidOperationException(
                    "[ZLua] Local zlua missing; run ZLua Install before Generate/All.");
            }

            string luaId = LuaVersionUtil.ResolveConfiguredOrDefault(
                Settings.Instance.luaVersionId, out _);
            if (!LuaVersionUtil.TryParse(luaId, out LuaVersionInfo luaInfo))
            {
                throw new InvalidOperationException($"[ZLua] Invalid luaVersionId: {luaId}");
            }

            WriteLocal(luaInfo, Application.unityVersion);
        }

        private static string EscapeCString(string s)
        {
            if (string.IsNullOrEmpty(s))
            {
                return string.Empty;
            }

            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
